### PR TITLE
Fix reconnect

### LINKED ISSUE #53: Retry doesn't increment retryCount
in NatsToCordaPipeline

### LINKED ISSUE #54: Corda connection monitoring not working correctly
RPC calls give errors, but watchdog doesn't see any problems

### LINKED ISSUE #56: Startingpoint of Nats subscriptions is incorrect
the listener starts at 'lastReceived' which means last received on the server not by the client.

Change it to using a timestamp saved on disk to resume from.

### PR DESCRIPTION
**Pull request by woutslakhorst**
and others:

- switched back to building using external nats server since embedded one isn't updated and therefore doesn't support > 0.17.0
-  fixed retry count not being incremented: Fixes #53
- Disconnected upstream Corda connection now disconnects Nats. Nats doesn't have a 'stop' function so disconnecting is the only option
- Extended exception catching for event handling, some corda connections were unknown. Fixes #54
- Changed starting point of nats subscription to where it previously left of using a timestamp stored on disk. Fixes #56

### CODE REVIEW

File: impl/src/main/kotlin/nl/nuts/consent/bridge/corda/CordaManagedConnection.kt [hunk 1]
```diff
@@ -40,60 +41,113 @@ import java.net.Socket
...
 
     private val logger: Logger = LoggerFactory.getLogger(this::class.java)
-    private var connection: CordaRPCConnection? = null
-    private var tryToConnect:Boolean = false
-    private var terminate:Boolean = false
-    private var retryCount = consentBridgeRPCProperties.retryCount
-    private var noConnectionReason: String? = "starting up"
-    private var watchdog: Thread? = null
+    private var cordaConnectionWatchdog: CordaConnectionWatchdog? = null
+    //private var retryCount = consentBridgeRPCProperties.retryCount
```
Comment (reinkrul) [inline impl/src/main/kotlin/nl/nuts/consent/bridge/corda/CordaManagedConnection.kt:45]: retryCount leftover?

File: impl/src/main/kotlin/nl/nuts/consent/bridge/corda/CordaManagedConnection.kt [hunk 2]
```diff
@@ -40,60 +41,113 @@ import java.net.Socket
...
-                            logger.info("Corda RPC connection established for $name")
-                            this.onConnected()
-                        } catch (e: IOException) {
-                            noConnectionReason = e.message // if host is unreachable
-                        } catch (secEx: ActiveMQSecurityException) {
-                            // Incorrect credentials
-                            noConnectionReason = secEx.message
-                        } catch (ex: RPCException) {
-                            noConnectionReason = ex.message
+    class CordaConnectionWatchdog(var managedConnection: CordaManagedConnection, var delay: Long, var onConnected: () -> Unit, var onDisconnected: () -> Unit, var onError: () -> Unit = {}): Runnable {
```
Comment (reinkrul) [inline impl/src/main/kotlin/nl/nuts/consent/bridge/corda/CordaManagedConnection.kt:49]: I think this class needs some documentation since it's quite a complex piece. What it solves, how it does so and how it should be used. Maybe some explanation on the implementation of run(...)

(would help in at least my understanding)

File: impl/src/main/kotlin/nl/nuts/consent/bridge/corda/CordaManagedConnection.kt [hunk 3]
```diff
@@ -40,60 +41,113 @@ import java.net.Socket
...
-        watchdog?.start()
+    }
+
+    fun noConnectionReason(): String? {
+        return cordaConnectionWatchdog?.noConnectionReason
+    }
+
+    private fun startThread() {
+        cordaConnectionWatchdog = CordaConnectionWatchdog(this, consentBridgeRPCProperties.retryIntervalSeconds.seconds.toMillis(), this.onConnected, this.onDisconnected)
+        Thread(cordaConnectionWatchdog).start()
```
Comment (reinkrul) [inline impl/src/main/kotlin/nl/nuts/consent/bridge/corda/CordaManagedConnection.kt:140]: maybe mark this as daemon thread to avoid it blocking JVM shutdown in abnormal situations?

File: impl/src/main/kotlin/nl/nuts/consent/bridge/nats/NatsManagedConnection.kt [hunk 4]
```diff
@@ -49,32 +50,43 @@ class NatsManagedConnection(val consentBridgeNatsProperties: ConsentBridgeNatsPr
...
-            // only create connection once, from there auto-reconnect handles all
-            if (connection == null) {
+        synchronized(this) {
+            logger.info("$name connected to Nats server")
+            try {
+                cf?.natsConnection = conn
+
+                // only create connection once, from there auto-reconnect handles all
+                // otherwise dupl clientID and dupl subscriptions
+                // if (connection == null) {
```
Comment (reinkrul) [inline impl/src/main/kotlin/nl/nuts/consent/bridge/nats/NatsManagedConnection.kt:82]: leftover code

File: impl/src/main/kotlin/nl/nuts/consent/bridge/corda/CordaManagedConnection.kt (hunk 1 above)
Comment (woutslakhorst) [reply impl/src/main/kotlin/nl/nuts/consent/bridge/corda/CordaManagedConnection.kt:45]: removed

File: impl/src/main/kotlin/nl/nuts/consent/bridge/corda/CordaManagedConnection.kt (hunk 3 above)
Comment (woutslakhorst) [reply impl/src/main/kotlin/nl/nuts/consent/bridge/corda/CordaManagedConnection.kt:140]: done

File: impl/src/main/kotlin/nl/nuts/consent/bridge/nats/NatsManagedConnection.kt (hunk 4 above)
Comment (woutslakhorst) [reply impl/src/main/kotlin/nl/nuts/consent/bridge/nats/NatsManagedConnection.kt:82]: removed
